import modules.OSCManager as osc

terrors = [
    "Huggy",
    "Corrupted Toys",
    "Demented Spongebob",
    "Specimen 8",
    "HER",
    "Tails Doll",
    "Black Sun",
    "Aku Ball",
    "Ao Oni",
    "Toren's Shadow",
    "[CENSORED]",
    "WhiteNight",
    "An Arbiter",
    "Specimen 5",
    "Comedy",
    "Purple Guy",
    "Spongefly Swarm",
    "Hush",
    "Mope Mope",
    "Sawrunner",
    "Imposter",
    "Something",
    "Starved",
    "The Painter",
    "The Guidance",
    "With Many Voices",
    "Nextbots",
    "Harvest",
    "Smileghost",
    "Karol_Corpse",
    "MX",
    "Big Bird",
    "Dev Bytes",
    "Luigi & Luigi Dolls",
    "V2",
    "Withered Bonnie",
    "The Boys",
    "Something Wicked",
    "Seek",
    "Rush",
    "Sonic",
    "Bad Batter",
    "Signus",
    "Mirror",
    "Legs",
    "Mona & The Mountain",
    "Judgement Bird",
    "Slender",
    "Maul-A-Child",
    "Garten Goers",
    "Don't Touch Me",
    "Specimen 2",
    "Specimen 10",
    "The LifeBringer",
    "Pale Association",
    "Toy Enforcer",
    "TBH",
    "DoomBox",
    "Christian Brutal Sniper",
    "Nosk",
    "Apocrean Harvester",
    "Arkus",
    "Cartoon Cat",
    "Wario Apparition",
    "Shinto",
    "Hell Bell",
    "Security",
    "The Swarm",
    "Shiteyanyo",
    "Bacteria",
    "Tiffany",
    "HoovyDundy",
    "Haket",
    "Akumii-kari",
    "Lunatic Cultist",
    "Sturm",
    "Punishing Bird",
    "Prisoner",
    "Red Bus",
    "Waterwraith",
    "Astrum Aureus",
    "Snarbolax",
    "All-Around-Helpers",
    "lain",
    "Sakuya Izayoi",
    "Arrival",
    "Miros Birds",
    "BFF",
    "Scavenger",
    "Tinky Winky",
    "Tricky",
    "Yolm",
    "Red Fanatic",
    "Dr. Tox",
    "Ink Demon",
    "Retep",
    "Those Olden Days",
    "S.O.S",
    "Bigger Boot",
    "The Pursuer",
    "Spamton",
    "Immortal Snail",
    "Charlotte",
    "Herobrine",
    "Peepy",
    "The Jester",
    "Wild Yet Curious Creature",
    "Manti",
    "Horseless Headless Horsemann",
    "Ghost Girl",
    "Cubor's Revenge",
    "Poly",
    "Dog Mimic",
    "Warden",
    "FOX Squad",
    "Express Train To Hell",
    "Deleted",
    "Killer Fish",
    "Terror of Nowhere",
    "Beyond",
    "The Origin",
    "Time Ripper",
    "This Killer Does Not Exist",
    "Parhelion's Victims",
    "Bed Mecha",
    "Killer Rabbit",
    "Random Flying Knife",
    "MissingNo",
    "Living Shadow",
    "The Plague Doctor",
    "The Rat",
    "Waldo",
    "Clockey",
    "Malicious Twins",
]

alternates = [
    "Decayed Sponge",
    "WHITEFACE",
    "Sanic",
    "Parhelion",
    "얀샋ㄷ요무",
    "Voidwalker",
    "The Knight Of Toren",
    "Tragedy",
    "Apathy",
    "MR MEGA",
    "sm64.z64",
    "Convict Squad",
    "Paradise Bird",
    "Angry Munci",
    "Lord's Signal",
    "Feddys",
    "TBH SPY",
    "The Observation",
    "Lisa",
    "Judas",
    "Glaggle Gang",
    "Try Not To Touch Me",
    "Ambush",
    "Teuthida",
    "Eggman's Announcement",
    "S.T.G.M",
    "Army In Black",
    "Lone Agent",
    "Roblander",
    "Fusion Pilot",
    "Joy",
    "The Red Mist",
    "Sakuya the Ripper",
    "Walpurgisnacht",
    "Dev Maulers",
    "Restless Creator",
    "Overseer",
]

eight_pages = [
    "Slendy",
    "Punishing Bird",
    "Snarbolax",
    "Sturm",
    "Arkus",
    "Cartoon Cat",
    "TBH",
    "Specimen 10",
    "Specimen 2",
    "Withered Bonnie",
    "MX",
    "Luigi",
    "Comedy",
    "Toren's Shadow",
    "Huggy",
    "Corrupted Woody",
    "Demented Spongebob",
    "HER",
    "Ao Oni",
    "Sawrunner",
    "Imposter",
    "With Many Voices",
    "The Guidance",
    "Big Bird",
    "Bacteria",
    "Akumii-kari",
    "Miros Bird",
    "Apocrean Harvester",
    "Legs",
    "This Killer Does Not Exist",
    "Judgement Bird",
    "All-Around-Helper",
    "ALTERNATES",
    "Slendy",
    "Slendy",
    "HoovyDundy",
    "Angry Munci",
    "Shadow Freddy",
    "Immortal Snail",
    "Herobrine",
    "Tinky Winky",
    "Jester",
    "Ghost Girl",
    "Warden",
    "Dog Mimic",
    "Red Mist Apparition ",
    "Baldi",
    "Living Shadow",
    "Clockey",
    "sm64.z64",
    "Searchlights",
]

def get_terror_names(round_type: str, killers_indexes: list) -> list[str]:

    osc.send_terrors(killers_indexes)

    match round_type:
        case "Run": return ["MeatBall Man", "", ""]
        case "8 Pages": return pages(killers_indexes)
        case "Alternate": return alternate(killers_indexes)
        case "Midnight": return midnight(killers_indexes)
        case  _: return standard(killers_indexes)

def standard(id: list) -> list[str]:
    slot_0 = terrors[int(id[0])]
    slot_1 = terrors[int(id[1])] if not int(id[1]) == 0 else ""
    slot_2 = terrors[int(id[2])] if not int(id[1]) == 0 else ""
    return [ slot_0, slot_1, slot_2 ]

def alternate(id: list) -> list[str]:
    slot_0 = alternates[int(id[0])]
    slot_1 = terrors[int(id[1])] if not int(id[1]) == 0 else ""
    slot_2 = terrors[int(id[2])] if not int(id[1]) == 0 else ""
    return [ slot_0, slot_1, slot_2 ]

def midnight(id: list) -> list[str]:
    slot_0 = terrors[int(id[0])]
    slot_1 = terrors[int(id[1])] if not int(id[1]) == 0 else ""
    slot_2 = alternates[int(id[2])] if not int(id[1]) == 0 else ""
    return [ slot_0, slot_1, slot_2 ]

def pages(id: list) -> list[str]:
    slot_0 = eight_pages[int(id[0])]
    slot_1 = ''
    slot_2 = ''
    return [ slot_0, slot_1, slot_2 ]